package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * 离线命令
 */
@Entity(nameInDb = "Cmd")
public class Cmd implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;

    @Property(nameInDb = "hexNo")
    private String hexNo;

    @Property(nameInDb = "cmdName")
    private String cmdName;

    @Property(nameInDb = "ext")
    private String ext;

    @Property(nameInDb = "cmdPwd")
    private String cmdPwd;

    @Property(nameInDb = "btAddress")
    private String btAddress;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Cmd() {
    }

    public Cmd(Long id) {
        this.id = id;
    }

    @Generated
    public Cmd(Long id, String hexNo, String cmdName, String ext, String cmdPwd, String btAddress) {
        this.id = id;
        this.hexNo = hexNo;
        this.cmdName = cmdName;
        this.ext = ext;
        this.cmdPwd = cmdPwd;
        this.btAddress = btAddress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 十六进制编号（例：0000）
     */
    public String getHexNo() {
        return hexNo;
    }

    /**
     * 十六进制编号（例：0000）
     */
    public void setHexNo(String hexNo) {
        this.hexNo = hexNo;
    }

    /**
     * 命令名称
     */
    public String getCmdName() {
        return cmdName;
    }

    /**
     * 命令名称
     */
    public void setCmdName(String cmdName) {
        this.cmdName = cmdName;
    }

    /**
     * 预留
     */
    public String getExt() {
        return ext;
    }

    /**
     * 预留
     */
    public void setExt(String ext) {
        this.ext = ext;
    }

    /**
     * 命令密码
     */
    public String getCmdPwd() {
        return cmdPwd;
    }

    /**
     * 命令密码
     */
    public void setCmdPwd(String cmdPwd) {
        this.cmdPwd = cmdPwd;
    }

    /**
     * 连接设备地址
     */
    public String getBtAddress() {
        return btAddress;
    }

    /**
     * 连接设备地址
     */
    public void setBtAddress(String btAddress) {
        this.btAddress = btAddress;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
