package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "Cmd".
 */
@Entity(nameInDb = "Cmd")
public class Cmd implements java.io.Serializable {

    @Id
    @Property(nameInDb = "hexNo")
    private String hexNo;

    @Property(nameInDb = "cmdName")
    private String cmdName;

    @Property(nameInDb = "ext")
    private String ext;

    @Property(nameInDb = "cmdPwd")
    private String cmdPwd;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Cmd() {
    }

    public Cmd(String hexNo) {
        this.hexNo = hexNo;
    }

    @Generated
    public Cmd(String hexNo, String cmdName, String ext, String cmdPwd) {
        this.hexNo = hexNo;
        this.cmdName = cmdName;
        this.ext = ext;
        this.cmdPwd = cmdPwd;
    }

    public String getHexNo() {
        return hexNo;
    }

    public void setHexNo(String hexNo) {
        this.hexNo = hexNo;
    }

    public String getCmdName() {
        return cmdName;
    }

    public void setCmdName(String cmdName) {
        this.cmdName = cmdName;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

    public String getCmdPwd() {
        return cmdPwd;
    }

    public void setCmdPwd(String cmdPwd) {
        this.cmdPwd = cmdPwd;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
