package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * 主界面配置
 */
@Entity(nameInDb = "Main")
public class Main implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;

    @Property(nameInDb = "type")
    private String type;

    @Property(nameInDb = "fontSize")
    private String fontSize;

    @Property(nameInDb = "gravity")
    private String gravity;

    @Property(nameInDb = "count")
    private String count;

    @Property(nameInDb = "x")
    private String x;

    @Property(nameInDb = "y")
    private String y;

    @Property(nameInDb = "width")
    private String width;

    @Property(nameInDb = "height")
    private String height;

    @Property(nameInDb = "hexNo")
    private String hexNo;

    @Property(nameInDb = "value")
    private String value;

    @Property(nameInDb = "btAddress")
    private String btAddress;

    // KEEP FIELDS - put your custom fields here
    private String unitStr="";
    // KEEP FIELDS END

    @Generated
    public Main() {
    }

    public Main(Long id) {
        this.id = id;
    }

    @Generated
    public Main(Long id, String type, String fontSize, String gravity, String count, String x, String y, String width, String height, String hexNo, String value, String btAddress) {
        this.id = id;
        this.type = type;
        this.fontSize = fontSize;
        this.gravity = gravity;
        this.count = count;
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
        this.hexNo = hexNo;
        this.value = value;
        this.btAddress = btAddress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 显示内容类别 0-变量，1-参数，2-图标，3-字符串，4-波形
     */
    public String getType() {
        return type;
    }

    /**
     * 显示内容类别 0-变量，1-参数，2-图标，3-字符串，4-波形
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * 字体大小 2-大字体，1-小字体，0-普通字体
     */
    public String getFontSize() {
        return fontSize;
    }

    /**
     * 字体大小 2-大字体，1-小字体，0-普通字体
     */
    public void setFontSize(String fontSize) {
        this.fontSize = fontSize;
    }

    /**
     * 对齐（2-中间，1-右对齐，0-左对齐）
     */
    public String getGravity() {
        return gravity;
    }

    /**
     * 对齐（2-中间，1-右对齐，0-左对齐）
     */
    public void setGravity(String gravity) {
        this.gravity = gravity;
    }

    /**
     * 小数点位数（0-7位）
     */
    public String getCount() {
        return count;
    }

    /**
     * 小数点位数（0-7位）
     */
    public void setCount(String count) {
        this.count = count;
    }

    /**
     * x坐标 显示行坐标 0-7行（以8像素为一个行单位）
     */
    public String getX() {
        return x;
    }

    /**
     * x坐标 显示行坐标 0-7行（以8像素为一个行单位）
     */
    public void setX(String x) {
        this.x = x;
    }

    /**
     * y坐标 显示列坐标 0-127列
     */
    public String getY() {
        return y;
    }

    /**
     * y坐标 显示列坐标 0-127列
     */
    public void setY(String y) {
        this.y = y;
    }

    /**
     * 显示区域宽度 1-128
     */
    public String getWidth() {
        return width;
    }

    /**
     * 显示区域宽度 1-128
     */
    public void setWidth(String width) {
        this.width = width;
    }

    /**
     * 显示区域高度 预留未使用 
     */
    public String getHeight() {
        return height;
    }

    /**
     * 显示区域高度 预留未使用 
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * 数据索引号,十六进制编号（例：0000）
     */
    public String getHexNo() {
        return hexNo;
    }

    /**
     * 数据索引号,十六进制编号（例：0000）
     */
    public void setHexNo(String hexNo) {
        this.hexNo = hexNo;
    }

    /**
     * 数据值
     */
    public String getValue() {
        return value;
    }

    /**
     * 数据值
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * 连接设备地址
     */
    public String getBtAddress() {
        return btAddress;
    }

    /**
     * 连接设备地址
     */
    public void setBtAddress(String btAddress) {
        this.btAddress = btAddress;
    }

    // KEEP METHODS - put your custom methods here
    public void setUnitStr(String unitStr){
        this.unitStr = unitStr;
    }
    public String getUnitStr(){
        return this.unitStr;
    }
    // KEEP METHODS END

}
