package com.bluetooth.modbus.snrtools2.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OfflineString".
*/
public class OfflineStringDao extends AbstractDao<OfflineString, Long> {

    public static final String TABLENAME = "OfflineString";

    /**
     * Properties of entity OfflineString.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HexNo = new Property(1, String.class, "hexNo", false, "hexNo");
        public final static Property StringZh = new Property(2, String.class, "stringZh", false, "stringZh");
        public final static Property StringEn = new Property(3, String.class, "stringEn", false, "stringEn");
        public final static Property BtAddress = new Property(4, String.class, "btAddress", false, "btAddress");
    }


    public OfflineStringDao(DaoConfig config) {
        super(config);
    }
    
    public OfflineStringDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OfflineString\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"hexNo\" TEXT," + // 1: hexNo
                "\"stringZh\" TEXT," + // 2: stringZh
                "\"stringEn\" TEXT," + // 3: stringEn
                "\"btAddress\" TEXT);"); // 4: btAddress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OfflineString\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OfflineString entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String hexNo = entity.getHexNo();
        if (hexNo != null) {
            stmt.bindString(2, hexNo);
        }
 
        String stringZh = entity.getStringZh();
        if (stringZh != null) {
            stmt.bindString(3, stringZh);
        }
 
        String stringEn = entity.getStringEn();
        if (stringEn != null) {
            stmt.bindString(4, stringEn);
        }
 
        String btAddress = entity.getBtAddress();
        if (btAddress != null) {
            stmt.bindString(5, btAddress);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OfflineString entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String hexNo = entity.getHexNo();
        if (hexNo != null) {
            stmt.bindString(2, hexNo);
        }
 
        String stringZh = entity.getStringZh();
        if (stringZh != null) {
            stmt.bindString(3, stringZh);
        }
 
        String stringEn = entity.getStringEn();
        if (stringEn != null) {
            stmt.bindString(4, stringEn);
        }
 
        String btAddress = entity.getBtAddress();
        if (btAddress != null) {
            stmt.bindString(5, btAddress);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OfflineString readEntity(Cursor cursor, int offset) {
        OfflineString entity = new OfflineString( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // hexNo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // stringZh
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // stringEn
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // btAddress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OfflineString entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHexNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStringZh(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStringEn(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBtAddress(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OfflineString entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OfflineString entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OfflineString entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
