package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "OfflineString".
 */
@Entity(nameInDb = "OfflineString")
public class OfflineString implements java.io.Serializable {

    @Id
    @Property(nameInDb = "hexNo")
    private String hexNo;

    @Property(nameInDb = "stringZh")
    private String stringZh;

    @Property(nameInDb = "stringEn")
    private String stringEn;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public OfflineString() {
    }

    public OfflineString(String hexNo) {
        this.hexNo = hexNo;
    }

    @Generated
    public OfflineString(String hexNo, String stringZh, String stringEn) {
        this.hexNo = hexNo;
        this.stringZh = stringZh;
        this.stringEn = stringEn;
    }

    public String getHexNo() {
        return hexNo;
    }

    public void setHexNo(String hexNo) {
        this.hexNo = hexNo;
    }

    public String getStringZh() {
        return stringZh;
    }

    public void setStringZh(String stringZh) {
        this.stringZh = stringZh;
    }

    public String getStringEn() {
        return stringEn;
    }

    public void setStringEn(String stringEn) {
        this.stringEn = stringEn;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
