package com.bluetooth.modbus.snrtools2.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OfflineString".
*/
public class OfflineStringDao extends AbstractDao<OfflineString, String> {

    public static final String TABLENAME = "OfflineString";

    /**
     * Properties of entity OfflineString.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property HexNo = new Property(0, String.class, "hexNo", true, "hexNo");
        public final static Property StringZh = new Property(1, String.class, "stringZh", false, "stringZh");
        public final static Property StringEn = new Property(2, String.class, "stringEn", false, "stringEn");
    }


    public OfflineStringDao(DaoConfig config) {
        super(config);
    }
    
    public OfflineStringDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OfflineString\" (" + //
                "\"hexNo\" TEXT PRIMARY KEY NOT NULL ," + // 0: hexNo
                "\"stringZh\" TEXT," + // 1: stringZh
                "\"stringEn\" TEXT);"); // 2: stringEn
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OfflineString\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OfflineString entity) {
        stmt.clearBindings();
 
        String hexNo = entity.getHexNo();
        if (hexNo != null) {
            stmt.bindString(1, hexNo);
        }
 
        String stringZh = entity.getStringZh();
        if (stringZh != null) {
            stmt.bindString(2, stringZh);
        }
 
        String stringEn = entity.getStringEn();
        if (stringEn != null) {
            stmt.bindString(3, stringEn);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OfflineString entity) {
        stmt.clearBindings();
 
        String hexNo = entity.getHexNo();
        if (hexNo != null) {
            stmt.bindString(1, hexNo);
        }
 
        String stringZh = entity.getStringZh();
        if (stringZh != null) {
            stmt.bindString(2, stringZh);
        }
 
        String stringEn = entity.getStringEn();
        if (stringEn != null) {
            stmt.bindString(3, stringEn);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public OfflineString readEntity(Cursor cursor, int offset) {
        OfflineString entity = new OfflineString( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // hexNo
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // stringZh
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // stringEn
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OfflineString entity, int offset) {
        entity.setHexNo(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStringZh(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStringEn(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(OfflineString entity, long rowId) {
        return entity.getHexNo();
    }
    
    @Override
    public String getKey(OfflineString entity) {
        if(entity != null) {
            return entity.getHexNo();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OfflineString entity) {
        return entity.getHexNo() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
