package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "Param".
 */
@Entity(nameInDb = "Param")
public class Param implements java.io.Serializable {

    @Id
    @Property(nameInDb = "hexNo")
    private String hexNo;

    @Property(nameInDb = "paramGroupHexNo")
    private String paramGroupHexNo;

    @Property(nameInDb = "type")
    private String type;

    @Property(nameInDb = "name")
    private String name;

    @Property(nameInDb = "value")
    private String value;

    @Property(nameInDb = "valueDisplay")
    private String valueDisplay;

    @Property(nameInDb = "linkVariable")
    private String linkVariable;

    @Property(nameInDb = "count")
    private String count;

    @Property(nameInDb = "unit")
    private String unit;

    @Property(nameInDb = "max")
    private String max;

    @Property(nameInDb = "min")
    private String min;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Param() {
    }

    public Param(String hexNo) {
        this.hexNo = hexNo;
    }

    @Generated
    public Param(String hexNo, String paramGroupHexNo, String type, String name, String value, String valueDisplay, String linkVariable, String count, String unit, String max, String min) {
        this.hexNo = hexNo;
        this.paramGroupHexNo = paramGroupHexNo;
        this.type = type;
        this.name = name;
        this.value = value;
        this.valueDisplay = valueDisplay;
        this.linkVariable = linkVariable;
        this.count = count;
        this.unit = unit;
        this.max = max;
        this.min = min;
    }

    public String getHexNo() {
        return hexNo;
    }

    public void setHexNo(String hexNo) {
        this.hexNo = hexNo;
    }

    public String getParamGroupHexNo() {
        return paramGroupHexNo;
    }

    public void setParamGroupHexNo(String paramGroupHexNo) {
        this.paramGroupHexNo = paramGroupHexNo;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getValueDisplay() {
        return valueDisplay;
    }

    public void setValueDisplay(String valueDisplay) {
        this.valueDisplay = valueDisplay;
    }

    public String getLinkVariable() {
        return linkVariable;
    }

    public void setLinkVariable(String linkVariable) {
        this.linkVariable = linkVariable;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getMax() {
        return max;
    }

    public void setMax(String max) {
        this.max = max;
    }

    public String getMin() {
        return min;
    }

    public void setMin(String min) {
        this.min = min;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
