package com.bluetooth.modbus.snrtools2.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ParamGroup".
*/
public class ParamGroupDao extends AbstractDao<ParamGroup, String> {

    public static final String TABLENAME = "ParamGroup";

    /**
     * Properties of entity ParamGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property HexNo = new Property(0, String.class, "hexNo", true, "hexNo");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Level = new Property(2, String.class, "level", false, "level");
    }


    public ParamGroupDao(DaoConfig config) {
        super(config);
    }
    
    public ParamGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ParamGroup\" (" + //
                "\"hexNo\" TEXT PRIMARY KEY NOT NULL ," + // 0: hexNo
                "\"name\" TEXT," + // 1: name
                "\"level\" TEXT);"); // 2: level
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ParamGroup\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ParamGroup entity) {
        stmt.clearBindings();
 
        String hexNo = entity.getHexNo();
        if (hexNo != null) {
            stmt.bindString(1, hexNo);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(3, level);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ParamGroup entity) {
        stmt.clearBindings();
 
        String hexNo = entity.getHexNo();
        if (hexNo != null) {
            stmt.bindString(1, hexNo);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(3, level);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ParamGroup readEntity(Cursor cursor, int offset) {
        ParamGroup entity = new ParamGroup( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // hexNo
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // level
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ParamGroup entity, int offset) {
        entity.setHexNo(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLevel(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ParamGroup entity, long rowId) {
        return entity.getHexNo();
    }
    
    @Override
    public String getKey(ParamGroup entity) {
        if(entity != null) {
            return entity.getHexNo();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ParamGroup entity) {
        return entity.getHexNo() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
