package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ParamGroup".
 */
@Entity(nameInDb = "ParamGroup")
public class ParamGroup implements java.io.Serializable {

    @Id
    @Property(nameInDb = "hexNo")
    private String hexNo;

    @Property(nameInDb = "name")
    private String name;

    @Property(nameInDb = "level")
    private String level;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ParamGroup() {
    }

    public ParamGroup(String hexNo) {
        this.hexNo = hexNo;
    }

    @Generated
    public ParamGroup(String hexNo, String name, String level) {
        this.hexNo = hexNo;
        this.name = name;
        this.level = level;
    }

    public String getHexNo() {
        return hexNo;
    }

    public void setHexNo(String hexNo) {
        this.hexNo = hexNo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
