package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * 键值对，替代sharepreference
 */
@Entity(nameInDb = "Value")
public class Value implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;

    @Property(nameInDb = "key")
    private String key;

    @Property(nameInDb = "value")
    private String value;

    @Property(nameInDb = "btAddress")
    private String btAddress;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Value() {
    }

    public Value(Long id) {
        this.id = id;
    }

    @Generated
    public Value(Long id, String key, String value, String btAddress) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.btAddress = btAddress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 主键
     */
    public String getKey() {
        return key;
    }

    /**
     * 主键
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * 值
     */
    public String getValue() {
        return value;
    }

    /**
     * 值
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * 连接设备地址
     */
    public String getBtAddress() {
        return btAddress;
    }

    /**
     * 连接设备地址
     */
    public void setBtAddress(String btAddress) {
        this.btAddress = btAddress;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
