package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * 键值对，替代sharepreference
 */
@Entity(nameInDb = "Value")
public class Value implements java.io.Serializable {

    @Id
    @Property(nameInDb = "key")
    private String key;

    @Property(nameInDb = "value")
    private String value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Value() {
    }

    public Value(String key) {
        this.key = key;
    }

    @Generated
    public Value(String key, String value) {
        this.key = key;
        this.value = value;
    }

    /**
     * 主键
     */
    public String getKey() {
        return key;
    }

    /**
     * 主键
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * 值
     */
    public String getValue() {
        return value;
    }

    /**
     * 值
     */
    public void setValue(String value) {
        this.value = value;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
