package com.bluetooth.modbus.snrtools2.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "Var".
 */
@Entity(nameInDb = "Var")
public class Var implements java.io.Serializable {

    @Id
    @Property(nameInDb = "hexNo")
    private String hexNo;

    @Property(nameInDb = "type")
    private String type;

    @Property(nameInDb = "count")
    private String count;

    @Property(nameInDb = "unit")
    private String unit;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Var() {
    }

    public Var(String hexNo) {
        this.hexNo = hexNo;
    }

    @Generated
    public Var(String hexNo, String type, String count, String unit) {
        this.hexNo = hexNo;
        this.type = type;
        this.count = count;
        this.unit = unit;
    }

    public String getHexNo() {
        return hexNo;
    }

    public void setHexNo(String hexNo) {
        this.hexNo = hexNo;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "===========hexNo==="+hexNo+",type==="+type+",count==="+count+",unit==="+unit;
    }

    // KEEP METHODS END

}
